ktor:
  deployment:
    port: 8080
  application:
    modules:
      - no.nav.helse.ApplicationKt.main

security:
  app_client_id: $AZURE_APP_CLIENT_ID
  app_client_secret: $AZURE_APP_CLIENT_SECRET
  app_scope: "api://dev-gcp.flex.flexjar-backend/.default"
  config_token_endpoint: $AZURE_OPENID_CONFIG_TOKEN_ENDPOINT
