ktor:
  deployment:
    port: 8080
  application:
    modules:
      - no.nav.helse.ApplicationKt.main

security:
  client_id: $AZURE_APP_CLIENT_ID
  client_secret: $AZURE_APP_CLIENT_SECRET
  scope: "api://${FLEXJAR_BACKEND_AAD_CLIENT_ID}/.default"
  config_token_endpoint: $AZURE_OPENID_CONFIG_TOKEN_ENDPOINT
  cors_allow_host: $CORS_ALLOW_HOST
